version: '3.9'

networks: 
  internalNet:
    name: internalNet

volumes:
  database:
    name: database
  images:
    name: images 

services:

  postgres:
    image: postgres:16-bookworm
    restart: "on-failure"
    container_name: postgres
    env_file: .env
    networks: 
      - internalNet
    ports: 
      - target: 5432
        published: 5432
    volumes:
      - database:/var/lib/postgresql/data
    shm_size: 128mb

  server: 
    build: ./server
    container_name: server
    restart: "on-failure"
    env_file: .env
    ports: 
      - target: 3000
        published: 3000
    networks: 
      - internalNet
    volumes:
      - images:/home/Backend/upload/
    depends_on:
      postgres:
        condition: service_started

  client: 
    build: ./client
    container_name: client
    restart: "on-failure"
    ports: 
      - target: 8080
        published: 8080
    networks: 
      - internalNet
    depends_on:
      postgres:
        condition: service_started
      server:
        condition: service_started
