version: '3.9'

networks: 
  internalNet:
    name: internalNet

services:

  postgres:
    image: postgres:16-bookworm
    restart: "on-failure"
    container_name: postgres_najib
    env_file: .env
    networks: 
      - internalNet

  server: 
    build: ./server
    container_name: server
    env_file: .env
    ports: 
      - target: 3000
        published: 3000
    networks: 
      - internalNet

  client: 
    build: ./client
    container_name: client
    env_file: .env
    ports: 
      - target: 8080
        published: 8080
    networks: 
      - internalNet
